services:
  manco:
    image: ghcr.io/hyaeve/manco:latest
    container_name: Manco
    network_mode: bridge
    ports:
      - 15600:15600
    volumes:
      - ./data:/app/data
      - ./downloads:/app/downloads
    environment:
      - TZ=Asia/Shanghai
    restart: unless-stopped